### ISSUE TITLE
picomatch npm package error

### ISSUE THREAD

**Issue by mayourdharukia** [pluralsight/web-dev-starter#10]
C:\Users\Mozavi-4\Desktop\web-dev-starter\node_modules\micromatch\index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, true);
                                                   ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Mozavi-4\Desktop\web-dev-starter\node_modules\browser-sync\dist\public\stream.js:3:18)
    at Module._compile (module.js:570:32)

npm ERR! Windows_NT 10.0.18362
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "code"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! js-starter-code@1.0.0 start: `lite-server "code"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-starter-code@1.0.0 start script 'lite-server "code"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-starter-code package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lite-server "code"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-starter-code
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-starter-code
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mozavi-4\Desktop\web-dev-starter\npm-debug.log

**Comment by mayourdharukia** [comment]
Not able to run web-dev-starter package due to this error.Pls someone help

**Comment by irmurphyAZ** [comment]
I received this error as well and corrected it by creating an account on GitHub and re-running.
